- main.py
- mordred.py
Initial skeleton for mordred daemon.
> Initial skeleton for mordred daemon

- main.py
- mordred.py
Creation of RQ workers is added based on the number of configuration
files. Also checks if RQ workers are already created
> Add basic creation for RQ workers based on configuration files

- main.py
- mordred.py
- utils/cfg_generator
```
luis@hogaza ~/repos/mordred/utils ±configuration_file_creator⚡ » python3 cfg_generator -h                        1 ↵
usage: cfg_generator [--help] [-o <file>] [-b <backends>]
optional arguments:
-h, --help            show this help message and exit
-b BACKENDS [BACKENDS ...], --backends BACKENDS [BACKENDS ...]
List of backends to be enabled
-o OUTPUT_FILE, --output OUTPUT_FILE
Output file
```
> Configuration file creator

- mordred.py
Add all activities related to SH included in the TaskSortingHat class.
> Add complete SortingHat support

- docker/README.md
[doc] Update the mordred docker sample doc with last features and config params added to mordred.
> [doc] Update the mordred docker sample doc

- menu.yaml
- mordred/task_panels.py
- Upload the panel for DockerHub
- Add a link to the proper panel on the main menu
> Add support for DockerHub

- LICENSE
- MANIFEST.in
- VizGrimoireUtils
- mordred/_version.py
- mordred/eclipse_projects_lib.py
- mordred/task_projects.py
- setup.cfg
- setup.py
New files (setup.py, setup.cfg) for creating a package.
Removing dependency from vizgrimoireutils (by copying a file from it).
It would be convenient to test with the Eclipse case, which was the reason why vizgrimoireutils was used, just in case my patch doesn't work properly...
> Adapt to produce a pipy package.

- menu.yaml
- mordred/config.py
- mordred/task_panels.py
Mordred now supports the loading of all panels and the aliases creation for them.
> [panels] Fix all panels issues

- mordred/task_identities.py
Until now we use a GitHub raw internal URL which included a token.
This URL won't work anymore after some days.
No we are using the GitHub Data API with an API token to get the file
contents.
> [task_identities] Fix downloading of identities file from GitHub

- mordred/config.py
- mordred/eclipse_projects_lib.py
- mordred/error.py
- mordred/github.py
- mordred/mordred.py
- mordred/task.py
- mordred/task_collection.py
- mordred/task_enrich.py
- mordred/task_identities.py
- mordred/task_manager.py
- mordred/task_panels.py
- mordred/task_projects.py
- mordred/task_report.py
- mordred/task_track.py
- tests/test_enrich_all.py
- tests/test_github.py
- tests/test_task.py
- tests/test_task_collection.py
- tests/test_task_enrich.py
- tests/test_task_identities.py
- tests/test_task_projects.py
- utils/find_affiliation_conflicts.py
- utils/projects_json2yml.py
> Fix all PEP-8 issues

- mordred/task_collection.py
The compute of the memory usage by the redis raw items dictionary is
pretty expensive once it is more than 100 MB. It is now only computed
once the last compute time x 5 has passed.
> [task_collection][arthur] Compute the memory usage in intervals

- mordred/task_collection.py
- mordred/task_enrich.py
Improve how the collection of raw items is done in projects with > 100 repositories.
Only try to create tasks in arthur if we have not done it already!
> Arthur memory dict

- grimoire_elk
- mordred/config.py
- mordred/mordred.py
- mordred/task_collection.py
- tests/test_task_collection.py
- tests/test_task_enrich.py
Configure bulk and scroll items size when using arthur for items collection.
> Arthur bulk and scroll items size

- mordred/task_collection.py
To avoid feeding items from redis at a higher speed that we can process them
don't feed items if the memory size of the pending items to be processed is
larger that ARTHUR_MAX_MEMORY_SIZE (500 MB).
> [arthur] Limit the max size of the python memory with raw items from redis

- docker/Dockerfile
- docker/stage
All the deployment is done from packages pip created using the git repositories
defined in requirements.cfg. To create these packages the script used is:
https://github.com/chaoss/grimoirelab/blob/master/utils/build_grimoirelab
> [docker] Update docker mordred image to use a install based on pip packages

- mordred/task_panels.py
Changes to interaction with Elasticsearch and Kibiter for supporting 6.x in both of them.
Main changes are in the following areas:
* Detection of the version of Kibiter/Kibana
* Uploading of Kibiter/Kibana configuration properties (such as default index pattern)
* Uploading of the main menu for the dashboard
* Use of mandatory header for Elasticsearch 6.x
This patch relies on other pathches to Kidash and GrimoireELK for supporting Elasticsearch and Kibiter/Kibana 6.x.
> [task_panlels] Support for Kibiter/Kibana 6.x

- mordred/mordred.py
- mordred/task_identities.py
- mordred/task_panels.py
- tests/test-projects.json
Kibiter now supports a title for the dashboard. New method for uploading it.
SortingHat now supports a new flag when initializing a database, to avoid an error message which was not really an error.
> [panels] Support latest changes in other componennts

- mordred/task_panels.py
The code was assuming that we had Kibana 4 or 5, and Kibana 6 was in fact assumed to be 4, because of the structure of if blocks. That prevented two-level menus for being correctly uploaded as such. Now, that's fixed.
> [task_panels] Fix support for Kibana 6 when uploading menus

- mordred/task.py
- mordred/task_collection.py
- tests/test-archive.cfg
- tests/test-projects-archive.json
- tests/test-projects.json
- tests/test.cfg
- tests/test_task_collection.py
- tests/test_task_enrich.py
This code enables the use of archive in mordred
> [archive] Allow handling archive

- mordred/task_collection.py
- mordred/task_enrich.py
- mordred/task_panels.py
Improve messages to the stdout so that users can figure out easier what Mordred is doing. Includes fixing some typos.
> [tasks] Improve messages

- mordred/task_collection.py
This code updates the import of the elastic class
> [task-collection] Update elastic import

- tests/test_task_collection.py
This code removes the initialization of the archive compressed file, which is not required anymore
> [tests] Remove archive compressed file

- mordred/config.py
- mordred/task.py
- mordred/task_enrich.py
- tests/archive-test.cfg
- tests/test.cfg
- tests/test_task_enrich.py
For each backend now the studies can be configured in mordred to be executed.
> Configure after enrichment studies per backend

- mordred/config.py
- mordred/task_identities.py
- tests/data/perceval_identities_sortinghat.json
- tests/data/remote_identities_sortinghat.json
- tests/test_task_identities.py
To activate the gender support in mordred you need to add:
[sortinghat]
...
gender = True
...
> [task_identities] Add gender support

- grimoire_elk
- mordred/eclipse_projects_lib.py
- mordred/task_projects.py
- tests/test_task_projects.py
Add support for extracting from Eclipse projects file the information about GitHub repositories so Eclipse dashboard could include GitHub data in it.
> Eclipse GitHub support

- mordred/config.py
- mordred/eclipse_projects_lib.py
- mordred/task.py
- mordred/task_collection.py
- mordred/task_enrich.py
- mordred/task_identities.py
- tests/test_task_identities.py
After changing the name of the file arthur to feeder (https://github.com/chaoss/grimoirelab-elk/pull/239), the import paths need to be update
> [arthur] Replace reference to file arthur

- doc/config.md
- mordred/config.py
- mordred/task_panels.py
Now the document with all the params included in the mordred config file is generated
automatically from the code.
All the params have now a description and the not used params have been removed.
> Document all modred config

- mordred/task_panels.py
- tests/archive-test.cfg
- tests/test.cfg
- tests/test_task_panels.py
The multi data source  visualizations are no Overview and Data Status panels
> [task_panels] Filter with data sources active only multi data source visualizations

- requirements.txt
This code allows to execute tests with the bleeding edge versions of the following grimoirelab components required by mordred:
- sortinghat
- manuscripts
- kidash
- elk
> [tests] Enable tests with latest versions of grimoirelab components

- mordred/task_manager.py
- tests/test_task_manager.py
This code include tests to check the methods of the TasksManager class.
> [tests] Add tests for task_manager

- mordred/eclipse_projects_lib.py
- mordred/task_projects.py
Convert from eclipse projects format to grimoire projects JSON format
> [task_projects] Add new eclipse_projects_lib.py

- README.md
- requirements.txt
- sirmordred/config.py
- tests/test_config.py
- tests/test_studies.cfg
This code describes the setup.cfg and projects.json, two files that drive the execution of the GrimoireLab platform.
> [doc] add readme.md

- .travis.yml
- sirmordred/config.py
- tests/test_task_panels.py
This code includes the coveralls badge to the READMDE.md. The travis.yml file has been modified accordingly.
> [docs] Add coveralls badge

- README.md
- tests/test-projects.json
- tests/test.cfg
- tests/test_config.py
This code updates the README.md and includes an example of GitLab within the tests/test.cfg file and tests/test-projects.json.
> [doc] Include example for GitLab

- tests/test_config.py
Add tests to check the enrich_pull_requests study and its parameters in test_studies.cfg
> [tests] Update test_config.py

- tests/test_task.py
- tests/test_task_enrich.py
- tests/test_task_panels.py
This PR fixes the tests for `task`, `task_enrich` and `task_panels`.
> [tests] Fix test mordred

- sirmordred/task_panels.py
This code modifies the alias defined for google hits indexes.
> [task_panels] Modify alias for google hits

- menu.yaml
- utils/menu.yaml
- utils/projects.json
- utils/setup.cfg
This code updates the jenkins panels within the menu.yml, which now includes two more panels for nodes and jobs respectively.
> [menu.yml] Update jenkins panels

- utils/setup.cfg
This code aligns the setup.cfg of the micro-mordred with the latest changes in the config.py, with the aim of easing testing tasks
> [utils] Update setup.cfg micro-mordred

- sirmordred/task_panels.py
The task for configuring panels created a wrong `.kibana` index before this one was created by Kibana. This code initializes `.kibana` index before doing any other operation. This index is created using 'kidash' tool - which uses the API provided by Kibana -.
This patch requieres of the activation of Kibana 6.x support in Kidash. See https://github.com/chaoss/grimoirelab-kidash/pull/23
> [tasks_panels] Fix initialization of .kibana index in Kibana 6.x

- utils/micro.py
This code enables micro mordred to handle exceptions thrown when executing raw and enrich tasks.
> [micro] Handle raw and enrich tasks exceptions

- README.md
- doc/config.md
This code updates the documentation in the README.md and doc/config.md, which now include info about how to enable gitlab issues and merge requests sections in panels.
> [doc] Update documentation with gitlab info

- sirmordred/task_panels.py
This code adds the panels about demography studies to the community section.
> [panels] Add demographics panel in community section

- setup.py
This code updates the versions of the dependencies used by Mordred.
> [setup] Update dependencies

- sirmordred/sirmordred.py
The necessary changes have been made as mentioned in issue #192
> resolving issue #192

- sirmordred/task_collection.py
- sirmordred/task_enrich.py
- sirmordred/task_identities.py
- sirmordred/task_panels.py
- sirmordred/task_projects.py
This code fixes the flake8 errors, that appear after the new release of the same package.
> [tests] Fix flake8 errors after upgrade

- menu.yaml
This PR updates menu.yaml to include new Git lifecycle
panel included in Sigils by https://github.com/chaoss/grimoirelab-sigils/pull/309
> [menu] Add Git Lifecycle panel

- sirmordred/task.py
- sirmordred/task_panels.py
This code includes a log message when the kibiter URL is wrong, which makes impossible to connect to Kibiter.
> [task_panels] Add log message when kibiter is not reachable

- menu.yaml
Needs https://github.com/chaoss/grimoirelab-sigils/pull/339
> Add jenkins job categories panel to `menu.yml`

- sirmordred/task_enrich.py
This code retrieves the metadata__timestamp value of the last item inserted in the enriched index before looping over the repos which data is stored in the same index. This is needed to make sure that
the incremental enrichment works for data sources that are collected globally but only partially enriched.
> [task_enrich] Pass the last timestamp of the index before enrichment

- utils/projects.json
- utils/setup.cfg
This code updates the setup.cfg and projects.json, which now includes the section to collect github repo stats.
> [utils] Update setup.cfg and projects.json of micro-mordred

- sirmordred/task_panels.py
Solved the YAMLLoadWarning by adding Loader parameter in yaml.load()
> YAMLLoadWarning solved

- menu.yaml
This code adds the panel to visualize the gerrit approvals.
> [menu.yml] Add gerrit approvals panel

- requirements.txt
- tests/archives-test-projects.json
- tests/test_config.py
This code updates the archives used to test the platform for github issues and pull requests. Furthermore, it fixes an assertion in the test `test_config` and freezes the requirements for elasticsearch and elasticsearch-dsl.
> [tests] Fix tests

- sirmordred/task_enrich.py
- sirmordred/task_manager.py
This PR includes log messages with INFO level in the files `task_enrich` and `task_manager` to provide the operator with information to better understand the execution of mordred.
> [logs] Add log INFO messages to task_enrich and task_manager

- README.md
related to https://github.com/chaoss/grimoirelab/issues/202
> [doc] Improve doc about `github-repos` param in panels section

- tests/test_config.py
- tests/test_studies.cfg
This code includes an example of gerrit and study sections.
> [tests] Add gerrit and its study sections

- README.md
> [doc] Update doc getting started

- requirements.txt
- setup.py
This code updates the redis dependency to version 3.0.0
> [mordred] Update redis dependency

- utils/setup.cfg
This code comments the params used to activate arthur which are not generally used.
> [utils] Comment arthur params in es-collection section

- README.md
This code enhances the documentation of mordred by describing
the projects.json file.
> [README.md] Add projects.json section

- README.md
> [doc] Refine README.md introduction

- README.md
> [doc] Update kibiter version to 6.1.4-5

- bin/sirmordred
- sirmordred/sirmordred.py
- sirmordred/task_enrich.py
- sirmordred/task_manager.py
This PR aims at improving the log messages and reducing the size of the logs.
Task manager logs are set to debug, since this information is available in the single tasks.
Refresh identities and projects logs are improved
> [mordred] Improve logs

- sirmordred/task_enrich.py
This code improves log messages of studies to clean our logs and
make it more readable
Signed-off-by: Quan Zhou <zhquan7@gmail.com>
> [studies] Improve log messages

- sirmordred/config.py
Adding required config for a new study that enables enriching a given index with some extra fields.
> [config] Add config fragment necessary for new study for adding extra fields.

- README.md
- doc/config.md
> [doc] Improve desc projects_url

- tests/test_config.py
- tests/test_studies.cfg
> [tests] Add tests for enrich_extra_data study

- tests/test_healthcheck.py
> [tests] Fix flake8 errors

- sirmordred/config.py
> [config] Add support for geolocation study

- tests/test_config.py
- tests/test_studies.cfg
> [doc] Add example for github2 sections

- README.md
Information about using labels was missing from the docs, so adding it here.
Signed-off-by: Ruth Cheesley <ruth.cheesley@acquia.com>
> Add info about labels

- README.md
Signed-off-by: Quan Zhou <zhquan7@gmail.com>
> [doc] Add an example of setup.cfg and projects.json for each data source

- README.md
> [readme] Improve doc to get a token for twitter

- README.md
Trouble shooting will help new developers overcome common problems while setting up Grimoire Lab.
> [doc] Added trouble shooting section to readme

- sirmordred/task_enrich.py
> Fixed phase enrichment time duration not counting days

- README.md
Hi @valeriocos , 
This PR is for adding Empty Index Problem and Solution in troubleshooting section of Readme file.
Please tell if something more has to be done.
Thankyou for your time
Signed-off-by: Kshitij Gupta kgupta3199@gmail.com
> Added Empty Index Problem in troubleshooting section of Readme

- README.md
This PR is to fix some spelling mistakes in Readme file
Signed-off-by: Kshitij Gupta <kgupta3199@gmail.com>
> correcting spelling mistakes in Readme

- README.md
Fixed username and password for kibiter login in troubleshooting section causing permission issue in elasticsearch while creating indexes
Signed-off-by: Nitish Gupta <imnitish.ng@gmail.com>
> fixed username and pass for kibiter login

- Getting-Started.md
This commit adds Troubleshooting section
to Getting-Started.md doc file.
A new issue, Low File Descripters ,has been added.
Signed-off-by: animesh <animuz111@gmail.com>
> [doc] Added Getting-Started doc

- Getting-Started.md
- README.md
Check out the new readme at https://github.com/abhiandthetruth/grimoirelab-sirmordred. Following are the changes made
* Added Trouble Shooting section in `Getting-Started.md`
* Added contents section for easier navigation.
* Listed Supported Resources contents for easier navigation
* Fixed some headings
* Removed Getting started and Troubleshooting from Readme.md
Just a question @valeriocos, Now that I have added Contents which makes the navigation much easier should we remove the getting started and troubleshooting section. Personally I like this format better but it may lead to 404 of old references of the sections. If possible we can add dummy sections in Readme.md, which instead of pouring the contents contains the link to …
> [doc]Refracted Readme.md

- README.md
Really sorry the previous pr had some linking issues a quick fix for that. Everything else checked.
> [doc]Fix broken backlinks in supported resources

- README.md
This PR fixes a typo in the setup.cfg and updates the data source link of the askbot configuration in the README.
> Fix askbot configuration typos

- Getting-Started.md
Signed-off-by: ria18405 ria18405@iiitd.ac.in
> Added sections in Troubleshooting

- Getting-Started.md
This commit adds to the Getting-Started
README PyCharm installation instructions.
Signed-off-by: animesh <animuz111@gmail.com>
> [doc] Add PyCharm installation instructions

- Getting-Started.md
Linked to https://github.com/chaoss/grimoirelab-sirmordred/issues/433
> Fixed a backlink

- Getting-Started.md
Signed-off-by: Ria Gupta <ria18405@iiitd.ac.in>
> [doc]Added section in 'How to' in Getting-Started.md

- Getting-Started.md
This commit adds information about how to change the menu, showing examples of the json and the steps to change it.
Signed-off-by: David Moreno <dmoreno@bitergia.com>
> Add "How to modify the menu" to the getting started guide

- Getting-Started.md
Installations:
- docker installation.
- docker-compose installation.
Troubleshooting:
- SSL error.
- cloc installation.
- git 'latest-item' error.
How-to : Dump a mapping/data from an index
- elasticdump installation.
- elasticdump execution.
> Updated getting-started and how-to section

- Getting-Started.md
I have added some sections to improve the 'How-To' section as per these suggestions (https://github.com/chaoss/grimoirelab-sirmordred/issues/439#issuecomment-602024254).
Signed-off-by: Ria Gupta <ria18405@iiitd.ac.in>
> Added some sections in 'How to' of GettingStarted document

- Getting-Started.md
Fixed some broken or inconsistent links in GettingStarted
Signed-off-by: Ria Gupta <ria18405@iiitd.ac.in>
> Fixed Broken Backlinks

- Getting-Started.md
Added section in How-to for resizing, renaming visualization and updating formats of attributes along with some reformatting.
> Added section in How-to for resizing, renaming visualization

- aliases.json
> [aliases] Fix enrich alias for gerrti

- sirmordred/task_panels.py
This code removes the support for Kibiter versions older than 6.x
> [task_panels] Remove support for Kibiter < 6.x

- tests/test_task.py
Related to https://github.com/chaoss/grimoirelab-elk/pull/888
> [tests] Add tests to process filter-no-collection on multi params URLs

- Getting-Started.md
This code updates the docker-compose files with the ES/Kibiter 6.8 images.
> [docs] Update getting-started with ES/Kibiter 6.8

- Getting-Started.md
The GrimoireLab got updated to a newer version (ES & Kibiter 6.8.6). This PR updates the Getting-Started.md installation result section with the latest snapshot of it.
I was thinking to leave the rest of the sections, for now, anticipating some new contributors. So, updating just the installation section.
> [docs] Update Getting-Started.md result image

- Getting-Started.md
Add info based on experience troubleshooting https://github.com/chaoss/grimoirelab/issues/338
> Add info about pulling in latest data

- README.md
- sirmordred/config.py
- tests/test_config.py
- tests/test_studies.cfg
The purpose of this study is to gather all the issues and pull requests which are mutually referenced. Once these
references are obtained, all of the events for the given issue or pull request are updated with the corresponding list of URLs from the referenced items.
README.md updated accordingly.
Tests added accordingly.
Note: This PR is related with the feature added in PR https://github.com/chaoss/grimoirelab-elk/pull/937.
> [githubql] Add new study "enrich_reference_analysis"

- README.md
- aliases.json
- requirements.txt
This new backend fetch changes from a weblate instance.
alias.json file updated accordingly.
README.md updated accordingly
> [requirements] Add new backend weblate

- README.md
This change shows how to add demography study for github
> [README] Add demography study for github

- .github/workflows/ci.yml
> [.github] Update elasticsearch to 6.8.6

- README.md
Currently it links to a page not found and I'm pretty sure this is a better place for the reader to be sent.
Signed-off-by: Michael Alexander <malexander@mgalexander.com>
> Refactoring link to new tutorial page.

- Getting-Started.md
- aliases.json
- poetry.lock
- pyproject.toml
- releases/unreleased/finos-meeting-backend-removed.yml
- requirements.txt
The backend is archived in its original repository and other GrimoireLab components already removed
it.
Signed-off-by: Santiago Dueñas <sduenas@bitergia.com>
> Remove support of FINOS Meetings backend

- .github/workflows/tests.yml
- poetry.lock
- pyproject.toml
- releases/unreleased/drop-python-3.6-support.yml
- releases/unreleased/include-requirements-for-development.yml
- requirements_dev.txt
Using Poetry by default install the latest version of the package from PyPI.
This PR includes a new file necessary for development and testing.
After poetry install you can run poetry run pip install -r requirements_dev.txt and it will install the latest version available in the master branch of the GrimoireLab repositories.
It also updates all the Grimoirelab packages to the latest version
> Include a new requirements for development and tests

- aliases.json
- releases/unreleased/github-pull-request-aliases-added.yml
> Add github:pull to aliases.json

- poetry.lock
- pyproject.toml
- requirements_dev.txt
Update Python version to 3.7.1 for Pandas
> Update Python version to 3.7.1 for Pandas

- .github/workflows/release.yml
This Pr updates the release workflow to create a test database
> [release] Update workflow to create the test database

- releases/unreleased/log-format-updated-with-the-mordred-project-name.yml
- sirmordred/bin/sirmordred.py
- sirmordred/utils/micro.py
This PR updates the logs for `sirmordred` and `micro`. It includes the name of the Modred project in the logs.
> Log format updated with the Mordred project name
