chaoss/grimoirelab-sirmordred

mordred.py
Now, adding new backends just need:
* Add the perceval backend params to the config file
* If params must be extracted from the repository URL implement in gelk ocean backend class the method get_perceval_params_from_url: https://github.com/grimoirelab/GrimoireELK/blob/master/grimoire/ocean/github.py#L36
=> [mordred] All perceval backend params are read from config file

mordred.py
This would make mordred to work with the new grimoire_elk module (please, accept this PR after accepting the one for grimoireELK, whcih implements that change).
Sidenote: when trying to run modred with the current GrimoireELK (master branch), I found that even for running `--help` there seems to be an error:
```
$ python mordred.py --help
Traceback (most recent call last):
File "mordred.py", line 41, in <module>
from grimoire_elk.panels import import_dashboard, get_dashboard_name
ImportError: cannot import name 'get_dashboard_name'
```
=> Change the name of grimoire module (now grimoire_elk).

bin/mordred, mordred/error.py, mordred/mordred.py, mordred/task.py, mordred/task_collection.py, mordred/task_enrich.py, mordred/task_identities.py, mordred/task_manager.py, mordred/task_panels.py, tests/test_task.py
Previous implementation was not raising correctly the exceptions, due to there was not method to control the exceptions launched from the mother/father process. 
How to reproduce the error?
- included this mbox data source in .json file
```
"mbox":[
"/home/luis/repos/mordred/mboxes"
]
```
- executed with update mode
- monitored the number of threads
```
watch -n1 "ps huH p `ps aux|grep mordred|grep python|awk {'print $2'}`"
```
- while the error is printed in the terminal were mordred was executed, the error is not logged and one of the threads dies
Current changes allow threads to share exceptions using a queue, so the main process can wait and read if any exception was raised and needs to be addressed.
The main process does not wait and check always, in this case the exception is raised …
=> Improve the Exception handling for threads by using queues. Fix T2031

mordred/error.py, mordred/github.py, tests/test_github.py
Github class will allow us to read files from Github using the token to access to private content. Future versions will also push content.
Future versions of Mordred will deal with Github files, some examples:
- reading identity files
- reading project files
- updating project files based on a Github organization and pushing its content
This is why this code is being added. I'm using it a development feature and I wanted to submit it asap so @zhquan can start adding tests to the extension of this library he worked on a weeks ago. See #16 
In order to test it, you'll need a parameter named 'github_token' under the 'general' section of the test.cfg file.
=> Add github.py library to deal with Github files

docker/Dockerfile
In order to save time, it's better to have pandas already installed in the image than installing it in the stage phase, as the compilation takes about 5 minutes.
=> Install pandas package in the Docker image

mordred/task_panels.py
In ElasticSearc/Kibana 5.6 the .kibana mapping is set to strict,
which means that new items must match the mapping.
This fix created a mapping for .kibana/metadashboard, which
overrides this, by setting "dynamic" to "true".
=> [task_panels] Fix mapping problem with ElasticSearch/Kibana 5.6

mordred/mordred.py, mordred/task_manager.py
Using the name parameter, when creating threads, the name of the thread
can be set. These names are a bit more meaningful that "Thread-3",
for example.
=> Add identification for threads

bin/mordred, mordred/config.py
Now -c accepts a list of configuration files, instead of only one. If only one is specified, it works as before.
If more than one is specified, all of them are read, in order. The paramerters they have cascade, that is,
parameters set in later files overwrite those set in previous files.
This is useful for splitting the configuration in several files. For example, all information related to the "local" setup (links and credentials for databases, for example) can be in one file, all information related to the characteristics of the dashboard in another (data sources, etc.), and all the information related to how to produce the dashboard (eg, `sleep`, `debug`, etc) in a third one. That way, we can have "generic" configurations that can be overridden for a particular purpose (such as having …
=> [config] Add variable number of configuration files

bin/mordred
Present the error causing a RuntimeError while reading configuration
in a slightly more friendly way to users.
=> [exceptions] Print RuntimeError in an appropriate way

mordred/config.py, mordred/task_identities.py
If this strict-mapping option is set to False during unify the matching
will be done using a no strict-mapping option so emails and names that
are not wellformed are used for matching also.
=> [task_identities] Add new option strict-mapping to sortinghat config

mordred/config.py, mordred/task_identities.py
With the sortinghat load command a param --reset could be provided
in order to unmerge all identities and remove the affiliations, so
the only affiliations and merging of identities come from the
identities file loaded.
=> [task_identities] Add reset_on_load param to activate the reset of identities on load

mordred/task_identities.py
The autorefresh identities list is built from unify output in a SortingHat state.
If we change this status before the refresh is done, for example
breaking identities in a load with reset, the autorefresh list won't
be valid anymore. Thus, until there iare no autorfresh identities,
the SortingHat state won't be changed loading identities.
=> [task_identities] Don't load identities if autorefresh is pending

mordred/task_identities.py
…rimoirelab2sh
If in mordred config file the option:
strict_mapping = false
is defined, then --no-email-validation is passed to grimoirelab2sh.
=> [task_identities] Add support for '--no-email-validation' option in grimoirelab2sh

mordred/config.py, mordred/mordred.py, tests/test_task_collection.py, tests/test_task_enrich.py
The option skip_initial_load has been removed because it is
not usable anymore.
Now the projects are loaded in the initial tasks in mordred and not
from Config class, a hacky place to do that.
=> [tasks_project] Load projects in the initial tasks in mordred

mordred/task_panels.py
Only upload (import) panels (dashboards) corresponding to the data sources in the mordred configuration.
This takes advantage of this new feature in kidash.
=> [tasks_panels] Add support for data sources when uploading panels.

mordred/task_collection.py
In redis the queue with raw items could be huge. In order to avoid issues
with the python memory dict with raw items, the items will be collected in
ARTHUR_REDIS_ITEMS packs (1000 by default).
=> [task_collection][arthur] Limit the total number of items collected from redis

mordred/task_panels.py, setup.py
grimoire-kidash is now kidash, and it is unbundled from grimoire-elk.
This patch should make mordred work with this new schema.
This patch should be applied after grimoirelab/grimoireelk#155
=> [panels] Use the new kidash module, instead of grimoire-kidash

mordred/task.py, mordred/task_collection.py, tests/test.cfg, tests/test_task_collection.py
This patch fixes the composition of params for perceval backends. The param 'fetch-cache' is replaced by 'no-cache', while int params are casted to string
=> [task] Fix composition perceval params

mordred/task_identities.py
Instead of getting the uids for identities to be refreshed
from the output of affiliate or unify, use the new last_modified field
to find the uids to be refreshed in the enriched indexes.
=> [task_identities] Use the new API SH call search_last_modified_identities to refresh identities

mordred/task_panels.py
Use http://kibiter:5601 instead of http://localhost:5601.
If we decide to continue with this approach, this Kibana URL will be defined in mordred config file.
=> [task_panels] Force the creation of .kibana index in Kibiter6 (update)

mordred/mordred.py, mordred/task_enrich.py, mordred/task_identities.py, mordred/task_manager.py
Now in the enrich process of each backend, the last modified uuids and uids
can be found and it can directly refresh those. Removed all the code needed
to communicate the identities to refresh from TaskIdentities to TaskEnrich tasks
which is not needed anymore.
=> Refactor autorefresh code thanks to the last_update field in Sortinghat

mordred/task_panels.py
In order to show the correct widgets in overview and data status panels
the data source to include in these panels is mbox, not pipermail. The
visualizations for both are the same.
=> [task_panels] Add mbox as data source to be shown if pipermail exists

mordred/task_identities.py
To avoid enriching data with identities that are not yet unified,
after the loading of identities, execute a unify process.
It is critial when loading identities with reset, because after the
loading of identities, all the identities loaded from data sources
are unmerged and unaffiliated because of the reset.
If the refresh of identities is done in this status the identities
in the enriched index will be "reseted" so all affiliations and
merging of identities will be lost.
=> [task_identities] Execute unify just after the load of identities in the same task

bin/mordred, mordred/config.py
Add the ability to setup and configure rotating log files via RotatingFileHandler.
If wanted this patch could be extended for supporting other file handlers as well.
Or possibly disabling file handlers and only logging to console (which might be good for some container setups)
=> setup and configure RotatingFileHandler for file logging

mordred/task.py, mordred/task_panels.py
Direct HTTM connnections were causing trouble when using ssl, in the case of wrong certificates. grimoire-elk connections are already having disabled, by default, checking the certificates. In addition, using grimoire-elk connections everywhere seems sensible. So, modify the code to use them in the only place (afaik) where they were not being used.
=> [tasks] Make use of grimoire-elk connections

tests/test_task_collection.py
This code mocks the value of the current datetime, which is used by the mediawiki backend. Thus, it allows to test the fetch_from_archive method of mediawiki
=> [tests] Mock datetime when testing mediawiki

mordred/task_panels.py, tests/menu.yaml, tests/test_task_panels.py
In panels JSON files, it is used stackoverflow instead of stackexchange.
=> [task_panels] Add as data source stackoverflow if stackexchange is included

mordred/task_manager.py
This code moves the report of possible exceptions triggered in the run method before the raise statement.
=> [TaskManager] Fix unreachable code

mordred/task_enrich.py, tests/test_task.py
This patch ensures that the variable `NUMBER_ENRICH_TASKS_ON` decreases in case of failures when executing enrichment tasks. Thus. it avoids possible infinite loops when loading identities.
=> [task_enrich] Ensure number of enrich tasks decreases upon failure

mordred/config.py, mordred/task_enrich.py, tests/test.cfg, tests/test_task_enrich.py
This code allows to define sections for studies (onion, demography and areas of code). In any backend section, a list of studies can be declared. Every declared study must have its parameters in a specific cfg section defined by type-of-the-study:study-id (e.g., enrich_onion:1). The id makes possible to execute the same types of studies for a given backend.
=> Enable study conf for backends via .cfg

mordred/config.py, tests/test.cfg, tests/test_task_enrich.py
This code enables to set up the `kafka_kip` study via the mordred configuration file. A test has been added within the test_task_enrich file to ensure the correct execution of study.
=> [studies] Allow setting up kafka_kip via cfg

mordred/task_enrich.py, tests/test-projects.json, tests/test.cfg, tests/test_task_enrich.py
This code allows to handle an empty list of studies within a backend section. In a nutshell, studies with empty names are filtered out from the list of studies. In case the filtered list is empty, a warning message is logged to notify the user.
=> [studies] Handle empty list of studies in backends

sirmordred/task_enrich.py
This code adds the ocean backend as parameter for studies. This modification is required since some studies need access to the raw index (which could be stored in a different machine).
=> [studies] Include raw backend to studies

requirements.txt
This code enables the inclusion of arthur and perceval eggs to the requirements.txt, thus allowing to test the full chain of grimoirelab using the master heads of all components.
=> [tests] Add arthur and perceval eggs to requirements.txt

sirmordred/config.py, tests/test.cfg, tests/test_config.py, tests/test_studies.cfg, tests/test_wrong.cfg
This code allows to include extra information in a backend section name, thus enabling the collection of different data for the same backend within the same cfg. This is the case for backends with multiple categories (e.g., GitHub).
=> [config] Add tag to backend sections

sirmordred/sirmordred.py, sirmordred/task_projects.py, tests/data/url-projects.json, tests/test-projects.json, tests/test.cfg, tests/test_config.py, tests/test_sirmordred.py, tests/test_task_manager.py, tests/test_task_projects.py
This code enables to load repos for a tagged backend sections. In the cfg, you can define multiple sections for the same backend using tags (e.g., github -> [github:issues], [github:pulls]), in the projects.json every entry has to be linked to a corresponding tagged section (e.g., "github:issues": [list of repos], "github:pulls": [list of repos].
=> Load repos for a tagged backend sections

sirmordred/config.py
This code adds `enrich_pull_requests` as one of the studies that can
be run, in the studies tuple in the `get_study_section` method.
This code helps add the functionality to to enrich pull requests only
index with additional fields. PRs related to this code are:
- https://github.com/chaoss/grimoirelab-sirmordred/pull/190
- https://github.com/chaoss/grimoirelab-elk/pull/419
=> [config] Add `enrich_pull_requests` to the tuple of studies

tests/test_studies.cfg
Add example of how to use the enrich_pull_requests study to the
test_studies.cfg file.
The enrich_pull_requests study should be done under the github:pull_requests
category and takes in an argument `raw_issues_index` which is the name
if the github issues raw index.
=> [tests] Add example of enrich_pull_requests study in test_studies.cfg

bin/sirmordred
This is just to fix a weird warning, see #192. See also chaoss/grimoirelab-kidash#15
This fix can be safely removed once the problem is fixed in the imported modules.
=> Fix weird warning

sirmordred/task_panels.py
It seems that last_month and affiliations panels are no longer in use. This patch removes them from the panels uploaded by default to Kibiter.
=> [panels] Remove unused panels

sirmordred/config.py, sirmordred/task_enrich.py
This code extends the cfg with the new parameter `autorefresh_interval` in section `es_enrichment`. When Mordred is launched, the `last_refresh_interval` is set to the current time minus the number of days defined in `autorefresh_interval` (by default 2). Thus all SH identities modified before that time are used to refresh the author data. In the other execution `last_refresh_interval` is set to the current time.
=> [config] Add time interval for autorefresh

sirmordred/config.py, sirmordred/task_panels.py, tests/test_task_panels.py
This code extends the config to include the option `onion` (set to true by default), which enables to create a new menu containing community information. The task_panels code has been modified accordingly.
=> [task_panels] Add community structure menu

utils/menu.yaml, utils/micro.py, utils/projects.json, utils/setup.cfg
This code proposes a tiny version of mordred to execute just once raw, merge identities, enrich, panels tasks of mordred on a given set of backends (declared in a cfg file passed as input). The micro-mordred overcomes the current limitations of the p2o script in ELK, which is not able to execute multiple studies for the input backend and requires constant changes to align its logic with the ELK one. The micro-mordred isn't supposed to require constant changes, since there is not gap between its logic and the mordred one.
In order to execute the micro-mordred on git and github, an example of the command is shown below:
`micro --raw --identities --enrich --panels --cfg ./setup.cfg --backends git github:issue github:pull`.
=> [utils] Add micro-mordred

menu.yaml, sirmordred/task_panels.py, utils/menu.yaml
Some typos were found related to the migration to Kibana 6.x panels.
This patch fixes them.
=> Fix typos for Kibana 6.x panels

menu.yaml
remo-activities panel uses only one index pattern. Two
were configured, probably due to a copy/paste from
remo-events panel, which follows a different approach.
=> [menu] Fix remo-activities index-patterns entry

menu.yaml
This index pattern was removed by previous commit
b1a75ba71b5ce18f9eb020f37c2bade6a8889567
because that index pattern did not exists in sigils repo.
Nevertheless, that index pattern is needed by data status
panel to work, so it has been added to sigils. This commit
adds the corresponding entry again to `menu.yaml` file.
=> [menu] Add index pattern for remo-activities

utils/setup.cfg
This code fixes the indexes declared in the git studies, which were pointing to indexes not created by micro-mordred.
=> [utils] Fix setup.cfg for micro-mordred

sirmordred/task_collection.py
Mediawiki supports two params now within the repo string,
this change adds support to extract the right one as tag.
=> [collection] Add support for mediawiki tag

menu.yaml, sirmordred/task_panels.py
This PR modifies `google hits` names (data source and backend name) to avoid losing widgets in the overview visualization.
=> [panels] Modify googlehits data source name

sirmordred/task_panels.py
If a panel does not have the release version, don't include it because
we can not detect if it is a newer version from the current one. Panels
without a release field are not supported in mordred anymore.
=> [task_panels] Do not import panels that don't have the release field

menu.yaml, sirmordred/task_panels.py, tests/test_task_panels.py, utils/menu.yaml
This PR extends the menu.yml and task_panels by including mbox-type entries,
such as hyperkitty, groupsio and nntp. Thus, enabling to visualize information in the dashboards.
=> Fix missing vis overview status

sirmordred/config.py, sirmordred/task_panels.py
This PR modifies the config and task_panels in order to enable kafka studies. In order to enable those studies, the param `kafka` within the section `panels` has to be set to `true`. By default
this study is disabled.
=> [panels] Handle kip/kafka panel

menu.yaml, sirmordred/task_panels.py
This PR enables to show maniphest and googlehits info in the overview and data status dashboards.
=> Fix visualizations for maniphest and googlehits data sources

sirmordred/task_collection.py
This code replaces the log message in the method ` __feed_arthur`, thus the terms 'Python dict' are changed in favour of 'Items queue', which could be a better understanding of the problem.
=> [task-collection] Improve logging message

README.md, doc/config.md, sirmordred/config.py, sirmordred/task_panels.py, tests/archives-test.cfg, tests/test.cfg, tests/test_studies.cfg, tests/test_task_panels.py, tests/test_wrong.cfg
This PR allows to set kibana configuration parameters, such as the default index pattern and time picker, which are taken directly from the mordred configuration file (.cfg). Furthermore, it keeps support for old ES+Kibana versions (<6).
The config.py has been changed accordingly, thus the parameter kibiter_url, within the section panels of the mordred cfg, is now mandatory. This change is needed to allow to configure default settings in kibana/kibiter dashboards. In addition, documentation (readme.md and config.md) has been aligned with the aforementioned changes.
Finally, tests have been changed according to the new aforementioned changes.
=> Fix default settings kibana (second proposal)

sirmordred/config.py, sirmordred/task_panels.py
This code extends the setup.cfg to load gitlab merge and issue panels on demand. When enabled (set to true), the attributes `gitlab_merges` and `gitlab_issues` allow to load the corresponding panels. By default these attributes are disabled.
=> [panels] Load gitlab panels by the setup.cfg

menu.yaml, sirmordred/config.py, sirmordred/task_panels.py, tests/test_task_panels.py, utils/menu.yaml
This code extends the setup.cfg to load mattermost panels on demand. When enabled (set to true), the attribute `mattermost` allows to load the corresponding panels. By default this attribute is disabled.
=> [panels] Load mattermost panels by the setup.cfg

sirmordred/config.py, sirmordred/task_panels.py, tests/test_task_panels.py
This code enhances `task_panels` to allow handling the way of loading panels according to a parameter (`strict`) within the setup.cfg. By default, the panels are loaded in strict mode, in order to disable it, it suffices to set `strict = false` within the section `panels` in the setup.cfg.
=> [panels] handle strict mode loading panels via setup.cfg

sirmordred/task_panels.py, utils/projects.json, utils/setup.cfg
This code creates aliases for gitlab indexes to visualize gitlab data. The expected aliases are `gitlab` for issues and `gitlab_merge` for merge requests. The name of the backend sections should be `gitlab:issue` and `gitlab:merge`.
=> [task_panels] Add aliases to gitlab indexes

sirmordred/task_panels.py
This code temporarily disables the configuration of the default index pattern and time picker for kibiter 6.
=> [tasks_panels] Disable kibiter 6 configuration

sirmordred/config.py, sirmordred/task_panels.py
This code changes the names of the params used to load gitlab issues and merges. The previous names were not aligned to the convention used by kidash to identify a data source.
=> [panels] Change gitlab param names

README.md, doc/config.md, tests/test_studies.cfg
This code updates the documentation for the `es_enrichment` section and onion studies.
The former includes a parameter `autorefresh_interval`, which defines the number of previous days (default 2) to be used to fetch modifications on the sortinghat database before executing the autorefresh. The latter contains a template to execute the onion study for gitlab merge requests and issues.
=> [doc] Update documentation for es_enrichement and onion studies

menu.yaml, utils/menu.yaml
This code removes the onion index pattern from the git panel. The micro mordred menu.yml has been changed accordingly.
=> [menu] Remove onion index pattern from Git panel

README.md, sirmordred/task.py, sirmordred/task_enrich.py
A new parameter `node_regex` can be specified in `setup.cfg`,
jenkins section, to clean node names vi regular expression.
Resulting name will be group 1 of the given RE or original
node name if RE doesn't match.
Needs https://github.com/chaoss/grimoirelab-elk/pull/460
=> [jenkins] Add support for node name cleaning

menu.yaml, utils/menu.yaml
This index pattern allows to build widgets based on
`resolution_date` instead of `grimoire_creation_date`.
Needed for: https://github.com/chaoss/grimoirelab-sigils/pull/284
=> [jira] Add index pattern for closed issues

bin/sirmordred, sirmordred/task_collection.py, sirmordred/task_enrich.py
Change the log level of the Perceval and GrimoireELK libraries when the parameter debug mode is set to false, this way the Mordred log is more readable. The files with the logs for those libraries are no longer used, so the tool will just write the logs to the current file all.log.
I thought about changing the logging level for GrimoireELK to avoid doing this, but this is going to take a lot of time and in any case, those messages should not be printed if everything works OK.
Besides changing the log level, the second small commit adds more info to the logging INFO messages to know the origin field both for the enrichment and collection phase. This is going to make easier to know what phase is being executed by anyone monitoring the log file.
=> Make standard logs more readable

sirmordred/sirmordred.py, sirmordred/task_manager.py
After having a look at the Mordred scheduler I've realized that the debug messages we have in the module named `task_manager` are not helping at all to debug how the threads are working. This is why I decided to improve them.
These changes unify the log debugging messages printed by the threads (and from the main process) using a thread identifier and a more clear text. See the example below:
```
2018-11-09 16:15:27,110 - sirmordred.task_manager - DEBUG - [thread:139935266682624][Global tasks] Thread starts
2018-11-09 16:15:27,285 - sirmordred.task_manager - DEBUG - [thread:139935266682624][Global tasks] Tasks will be executed in this order: [<sirmordred.task_panels.TaskPanels object at 0x7f4537dde710>, <sirmordred.task_panels.TaskPanelsMenu object at 0x7f4537594940>] …
```
=> Unify the log debug messages printed by the threads

sirmordred/task_enrich.py
This code refactors the `refresh_identities` method to align it with the recent changes in the sortinghat api. In a nutshell, in order to reduce the memory footprint, the sortinghat api returns a generator of identities (instead of lists), the refresh_identities method manipulates this list to prepare a filter used to update the data with the identities information updated. Furthermore, the log message has been modified to reduce the information printed.
=> [task-enrich] Refactor `refresh_identities`

sirmordred/config.py, sirmordred/task.py, sirmordred/task_collection.py, sirmordred/task_enrich.py, tests/archives-test.cfg, tests/test_studies.cfg, tests/test_wrong.cfg
This code enhances the setup.cfg to include a new param `aliases_file`, which allows to declare the file path of a JSON file containing aliases for raw and enriched indexes.
=> [aliases] Add aliases_file to cfg

sirmordred/task_panels.py
Affiliations panel is available since GrimoireLab 0.2.0 but it is not managed by Mordred. This patch fixed this problem uploading the panel and its index patter, plus, adding an entry to Community section on the menu.
=> [task_panels] Add Affiliations panel

sirmordred/task_panels.py
This code includes the efficiency panels for GitLab merge requests and issues. Both panels are automatically loaded when enabling the params `gitlab-issues` and `gitlab-merges` in the `panels` section of the setup.cfg
=> [task_panels] Add GitLab efficiency panels

sirmordred/task_enrich.py
This PR allows to propagate the cfg section name of a backend to ELK. This information is needed to correctly retrieve the project name within the projects.json. 
This PR should be reviewed together with https://github.com/chaoss/grimoirelab-elk/pull/530
=> [task_enrich] Propagate cfg section name to ELK

sirmordred/task_panels.py
This core replaces the urljoin method of urllib.parse with the method urijoin of grimoirelab-toolkit.
=> [task_panels] Replace urljoin with urijoin

sirmordred/task_identities.py
This code includes an error log message when the orgs_file is not found on disk.
=> [task_identities] Log message when orgs_file is not found on disk

README.md, doc/config.md, sirmordred/config.py, sirmordred/task.py, sirmordred/task_collection.py, sirmordred/task_enrich.py, sirmordred/task_projects.py, sirmordred/task_track.py, tests/test_task_projects.py
This PR allows to set up the global data source from the setup.cfg using the param `global_data_sources` in the `general` section. By default the global data sources are: bugzilla, bugzillarest, confluence, discourse, gerrit, jenkins, jira. 
Test and the related code has been changed accordingly.
=> [mordred] Make global sources configurable from cfg

sirmordred/config.py, sirmordred/task.py, sirmordred/task_collection.py, sirmordred/task_enrich.py, sirmordred/task_projects.py, sirmordred/task_track.py, tests/test_task_projects.py
This PR is an attempt to address the comments at https://github.com/chaoss/grimoirelab-sirmordred/pull/269. Thus this code removes the global data sources parameter, which is now automatically assessed based on the projects.json. In a nutshell, if a given data source appears in the section `unknown` of the projects.json and in another section, that data source is considered global. Thus, meaning that the all data is collected but just a portion of it is finally enriched.
=> [mordred] Remove global data sources param

sirmordred/config.py
This code fixes the flake8 F632 error, which occurs when comparing str, bytes, and int literals with operators different from ==/!=.
=> [config] Fix flake8 error

README.md, doc/config.md
This code documents the use of micro-mordred, which provides a simplified version of mordred to run single mordred tasks (e.g., collection, enrichment) per execution.
=> [doc] Add documentation about micro-mordred

sirmordred/task.py, sirmordred/task_collection.py
This code refactors the logic to process the filter-raw, plus it also adds some documentation to better explain why url with filter-raw are ignored during the collection phase.
Note that the code at: https://github.com/chaoss/grimoirelab-sirmordred/compare/master...valeriocos:filter-raw-ref?expand=1#diff-acf081d06eea60ca1f99f5361dba311bL207 smells bad. 
Let's suppose we have the following conf:
```
"grimoire": {
"git": [
"https://github.com/chaoss/grimoirelab-elk --filter-raw=data.files.action:M"
],
"unknown": {
"git": [
"https://github.com/chaoss/grimoirelab-elk"
],
[git]
raw_index = git_chaoss_x
enriched_index = git_chaoss_x_enriched_y
latest-items = true
studies = [enrich_onion]
```
In this case, the filters are ignored because the method …
=> [mordred] Handle filter raw in task and task-collection

README.md, doc/config.md, sirmordred/config.py, sirmordred/task.py, sirmordred/task_collection.py, sirmordred/task_enrich.py
This PR allows to remove the data from raw, enriched and studies indexes based on the new config param `retention_horus`. In a nutshell, the attribute allows to declare the maximum number of hours after which the data must be removed from the platform. After the end of the collection and enrichment phases, a `delete_by_query` operation is triggered on the target index.
=> [sirmordred] Enforce data retention policy

sirmordred/task_projects.py, tests/test-repos-projects.json, tests/test-repos.cfg, tests/test_task_projects.py
This PR refactors the method `get_repos_by_backend_section` in
order to support the following actions:
- collect the raw data when a repo is only declared in the `unknown`
section
- enrich the data when a repo is only declared in the `unknown`
section
=> [task_projects] Refactor `get_repos_by_backend_section`

aliases.json, requirements.txt
This code includes the repo https://github.com/Bitergia/grimoirelab-perceval-finos to the requirements.txt file. Furthermore, it also updates the aliases.json to include the aliases for the raw and enriched indexes of finosmeetings data.
=> [mordred] support finosmeetings data

sirmordred/task_projects.py
This code prevents to globally enrich data sources declared in the unknown section and in other sections.
=> [task_projects] Prevent enrich unknown projects when declared also in other projects

README.md, aliases.json, doc/config.md, menu.yaml, sirmordred/config.py, sirmordred/task_panels.py, tests/aliases.json
This PR allows to upload the jenkins export and github repos panels by setting the params `jenkins-export` and `github-repos` to true in the section `panels` of the setup.cfg. By default these params are disabled. Furthermore, the aliases.json file has been modified to include the aliases for the raw and enriched indexes related to the github repositories data
=> Upload jenkins export and github repos panels

README.md, doc/config.md, sirmordred/config.py, sirmordred/task.py, sirmordred/task_collection.py, sirmordred/task_enrich.py
This code allows to retain only the identities that have been seen after a give date (defined in terms of minutes wrt to the current time, `retention_time`).
=> [task_enrich] Support retain identities

README.md
This code fixes the first example to execute micro mordred which was missing the param `--cfg`.
=> [doc] Fix missing --cfg param for micro mordred example

sirmordred/task_collection.py, sirmordred/task_enrich.py
This PR allows to forward the url of a specific repo within the projects.json to elk (`feed_backend` and `enrich_backend` functions). This change is needed to simplify the assignment of the repo to the project
defined in the projects.json. The functions `feed_backend` and `enrich_backend` now accepts a new param (set to None by default to not break existing functionalities) `projects_json_repo`.
=> [mordred] Pass repo url in projects.json to ELK

sirmordred/config.py, tests/test_studies.cfg
This PR adds a study to process git branches. It is activated by adding the section [enrich_git_branches]
in the setup.cfg, it doesn't require any param, and it applies to the enriched index.
An example of this study has been added to tests/test_studies.cfg
=> [config] Add study to process git branches

aliases.json
This code updates the name of the alias used for gitlab issues, which now is `gitlab_issues`.
=> [aliases.json] Rename alias for gitlab issues

aliases.json
`gitlab` alias is misleading, `gitlab_issues` is the right one.
Signed-off-by: Alberto Pérez García-Plaza <alpgarcia@bitergia.com>
=> [alias] Remove gitlab alias

utils/micro.py
Logging configuration is set up at module scope. This overrides the configuration defined in config_logging() function, making to show DEBUG messages when the its flag is not active.
This patch fixes this problem removing the setup at module scope.
Fixes #295
=> Fix logging configuration at module scope

utils/grimoirelab_valid.yml, utils/micro.py
This code allows to load identities from micro-mordred. This can be achieved by using the param --identities-load. An example of identities file is also included.
=> [utils-micro] Add support to load identities in micro

sirmordred/task.py, sirmordred/task_collection.py, sirmordred/task_enrich.py
This code allows to add labels to the repositories, thus providing further classifications based on the customer needs. The labeling is achieved by adding `--labels=[a, b, c]` within the projects.json
lines (e.g., `https://github.com/chaoss/grimoirelab-perceval --labels=[collection]`).
It is worth noting that labels info are extracted from the projects.json and filtered when loading the projects.json in ELK in order to avoid breaking already existing functionalities.
=> [mordred] Add repo labels support

sirmordred/task_enrich.py
This PR updates the statement that initializes the Elasticsearch objects (imported from the library elasticsearch) to use RequestsHttpConnection as connection class, thus avoiding `elasticsearch.exceptions.SSLError: ConnectionError exceptions`
=> [task_enrich] Fix elasticsearch.exceptions.SSLError: ConnectionError

.gitignore
This code adds the .gitignore file to mordred. In particular, it prevents to upload the setup.cfg and projects.json used by micro.py in utils/.
=> [mordred] Add .gitignore

README.md
When generating a package for Pypi, it doesn't like the rst file automatically generated from the README.md file. This patch fixes that.
The problem can be checked with "twine check pkg", being pkg the generated package, via "python setup.py bidst_wheel" or "python setup.py sdist".
=> Fix README.md so that the package is admitted by pypi.

sirmordred/task_enrich.py
This code allows to create the identities index only when the retention policy is active, thus avoiding slowing down the enrichment processes on the platform.
=> [task_enrich] Populate identities index only when retetion is on

sirmordred/task_collection.py, tests/test_task_collection.py
This PR enhances the task collection by making it return a list of errors info for each repo. The list
is shaped as follows:
```
[
{
'backend: 'GitHub',
'repo': 'https://github.com/chaoss/grimoirelab-perceval',
'error': 'RateLimit error ...'
}
]
```
=> [task_collection] Return errors info for task collection

.travis.yml, requirements.txt, setup.py
This PR cleans the content of the travis.yml, requirements.txt and setup.py by avoiding installing packages which are installed by other GrimoireLab components. It also aligns the requirements.txt with the install_requires in the setup.py
=> Polish travis, requirements.txt and setup.py

README.md
This code defines the versions of ElasticSearch, Kibiter (downstream of Kibana) and MySQL/MariaDB currently used in prd environments. This PR is related to https://github.com/chaoss/grimoirelab-sirmordred/issues/318
=> [doc] State Elasticsearch, Kibana, MySQL/MariaDB versions

requirements.txt, sirmordred/config.py, sirmordred/task_panels.py, tests/test_config.py, tests/test_studies.cfg
- Added the configuration required to trigger enricher and study integration of Graal from ELK. 
> **Note:** The tests would fail until we merge https://github.com/chaoss/grimoirelab-elk/pull/672
/cc @valeriocos 
Signed-off-by: inishchith <inishchith@gmail.com>
=> [graal] Add configuration for Graal integration in ELK

README.md, utils/projects.json, utils/setup.cfg
This PR enhances the setup.cfg and projects.json by including some examples about how to use graal backends. Furthermore, it also updates the READEME.md with the description of two attributes used to load graal panels:
- code-license, upload license dashboard
- code-complexity, upload code complexity dashboard.
=> [doc] Update README and examples to use graal backends

sirmordred/task_projects.py, tests/test_task_projects.py
This code replaces the logic used to calculate the diff between two projects.json files with a
comparison between the hashes of the files. This change has been done since the previous comparison took into account only the projects added/removed from the files (and not the repos), and replicate this at repo level would add some extra complexity which is not needed.
Tests have been modified accordingly.
=> [task_projects] Remove projects_last_diff

README.md, doc/config.md, sirmordred/config.py, sirmordred/task_panels.py
This commits adds the param "contact" to the setup.cfg, this param
is an URL optional that will redirect the user to the support
repository. Therefore, the About item in the menu is now a submenu
with two children, a link to About the dashboard and the link to the
"contact" URL.
Signed-off-by: David Moreno <dmorenolumb@gmail.com>
=> [task_panels] Add contact link inside the About item of the menu

sirmordred/task_identities.py, tests/test_task_identities.py
This PR provides a mechanism to load organization and identities files when a change is detected in their content. In a nutshell, for every organization/identities file, a hash is generated based on its content and stored in `TaskIdentitiesLoad`. If a change is detected on the file hash, the corresponding file is entirely reloaded.
This PR adds also a log message about the number of organizations loaded (it resolves a FIXME comment).
Note that:
1) the initial loop will load organization/identities file, even if the data is already in SortingHat. Adding addtional checks to inspect the database is out of the scope of this PR.
2) if the `reset_on_load` param is set to True, the identities files will be reloaded at every loop.
3) Diff detection and loading of new organization/identities in …
=> [task_identities] Lazy loading of orgs and identities files

sirmordred/task_collection.py, tests/test-no-collection.cfg, tests/test-projects-no-collection.json, tests/test_task_collection.py
This code allows to prevent the collection of repositories listed in the 
projects.json by adding `--filter-no-collection=true` to the corresponding lines.
Tests have been provided accordingly.
An example of projects.json is shown below:
```
{
"grimoire": {
"git": [
"https://github.com/VizGrimoire/GrimoireLib --filter-no-collection=true",
"https://github.com/MetricsGrimoire/CMetrics"
]
}
}
```
=> [task_collection] Add filter-no-collection to ignore the collection

sirmordred/sirmordred.py, sirmordred/task.py, sirmordred/task_enrich.py, sirmordred/task_identities.py, tests/data/url-projects.json, tests/test-no-sh.cfg, tests/test_task_collection.py, tests/test_task_enrich.py, tests/test_task_projects.py
This code allows to decouple sortinghat from the rest of the platform. It worth mentioning that the platform will fail in case the `identities` phase is enabled and the `sortinghat` section is not given in the setup.cfg 
Related to https://github.com/chaoss/grimoirelab-sirmordred/issues/342
=> [mordred] Make sortinghat optional

sirmordred/task_projects.py
This code guarantees that the repos loaded from the projects.json are always returned in the same order. This is ensured by using the `sort` standard method.
Related to #346
=> [task_project] Prevent random shuffling of repos

sirmordred/task_enrich.py
This code changes the `last_enrich_date` value by avoiding settings to zero seconds and milliseconds. This change is needed to avoid enriching over and over the last Git
items.
=> [task_enrich] Change `last_enrich_date` value

.travis.yml
This code extends the tests executed on mordred to python 3.5 and 3.6.
=> [travis] Support tests for python 3.5 and 3.6

sirmordred/task_identities.py
This code makes sure to call the unify operation of SortingHat when loading an identity file. Furthermore,  also the SH affiliate operation is called at the same time, when the affiliate
param is set to True.
=> [task_identities] Call sh unify/affiliate after loading identites file

sirmordred/task.py
When we made sortinghat optional: https://github.com/chaoss/grimoirelab-sirmordred/pull/341 we forgot to change this line
=> [sortinghat] Fix issue when sortinghat is not in the config file

README.md, doc/config.md, docker/README.md, sirmordred/config.py, sirmordred/task_identities.py, tests/archives-test.cfg, tests/data/task-params-test.cfg, tests/test-no-collection.cfg, tests/test-repos.cfg, tests/test.cfg, tests/test_studies.cfg, tests/test_wrong.cfg
This code decomissions the sortinghat params `bots_names` and `no_bots_names` from the setup.cfg. Task identities, config, tests data and documentation have been updated accordingly.
Related to https://github.com/chaoss/grimoirelab-sirmordred/issues/369
=> [mordred] Decommission bot names params from setup.cfg

README.md, bin/sirmordred, doc/config.md, sirmordred/config.py
This PR removes support to log rotation so the parameters 'log_file_handler', 'max_bytes' and 'backup_count' are not longer valid in config.py. These params are removed from 'setup_logs()' and config.md and README.md have been updated accordingly. Furthermore, this PR removes from 'bin/sirmordred' the imports for configparser, traceback, ElasticSearchError and DatacollectionError since not used , and finally log messages are formatted with 'format()' with the aim of aligning them to the recent changes in ELK.
=> [sirmordred] Delete support to log rotation

aliases.json, sirmordred/task_panels.py
This code includes the OSPO panels (listed below) in the standard dashboards shipped with grimoirelab. Furthermore, the aliases.json file is updated to automatically set the alias needed to visualize their data.
- contributors_growth
- engagement_by_contributors
- organizational_diversity
- orgnizational_diversity_by_domains
Below, the snippet of the new community menu:
=> [task_panels] Include OSPO panels in community menu

docker/README.md
This code removes information about the track_items feature, which is not supported anymore by Mordred.
=> [docker] Remove track_items info from readme

README.md
The purpose of this PR is described in https://github.com/chaoss/grimoirelab/issues/264
=> Made gitlab issues naming consistent. Fixes chaoss/grimoirelab#264

README.md
This code complets the list of data sources by including the ones defined in the perceval children (for puppet, opnfv and mozilla).
=> [doc] Complete list of data sources supported

tests/test_task_collection.py, tests/test_task_enrich.py
This code avoids to execute the project task for each backend within `test_execute_from_archive` for the task_collection tests. Furthermore, it also includes a new test for the task_enrich which relies on archive data.
=> [tests] Improve tests for task_collection and task_enrich

README.md, aliases.json, doc/config.md, sirmordred/config.py, sirmordred/task_panels.py
This code provides the means to automatically upload the github comments dashboard, useful to understand the community interactions on issue and pull request comments.
The dashboard can be activated by setting `github-comments` to true in the section `panels` of the setup.cfg. Note that the setup.cfg should also include the sections `github2:pull` and `github2:issue`.
```
[panels]
kibiter_time_from= "now-2y"
kibiter_default_index= "git"
kibiter_url = http://admin:admin@localhost:5601
github-comments = true <-----
[github2:issue]
api-token = xxx
raw_index = github_chaoss
enriched_index = github_chaoss_180322_enriched_200123
sleep-for-rate = true
no-archive = true
[github2:pull]
api-token = xxx
raw_index = github-prs_chaoss
enriched_index = github-prs_chaoss_190830_enriched_200123 …
```
=> [panels] Upload github-comments dashboard

aliases.json
This code reshapes the aliases.json, which now is able to handle complex aliases. The new format
allows to define a list of aliases with/without filters. An example of a new alias is provided below:
```
"github2:issue": {
"raw": [
{
"alias": "github2_issues-raw"
}
],
"enrich": [
{
"alias": "github2_issues"
},
{
"alias": "github2_pull_requests",
"filter": {
"terms": {
"issue_pull_request" : [
"true"
]
}
}
},
{
"alias": "affiliations"
},
{
"alias": "all_enriched"
}
]
},
```
Addresses to: https://github.com/chaoss/grimoirelab-sirmordred/issues/388
Related to: https://github.com/chaoss/grimoirelab-elk/pull/771
=> [aliases] Handle complex aliases

sirmordred/task.py, sirmordred/task_enrich.py
This code removes the support to include author and committer information extracted from github commits, when enriching git data. Thus, the code used to initialize the github token needed to query the API is removed.
Review together with https://github.com/chaoss/grimoirelab-elk/pull/773
Deprecates https://github.com/chaoss/grimoirelab-sirmordred/pull/384
=> [sirmordred] Remove support for github commit

.travis.yml
This code extends the CI tests to python 3.7
=> [travis] Support python 3.7

aliases.json
This code removes the old aliases set for github2 indixes.
=> [aliases.json] Remove old github2 aliases

README.md
When you add new data sources in the 'setup.cfg' after the first execution
you have to manually remove those dashboards and restart the mordred
process to upload them again with the new widgets.
Signed-off-by: Quan Zhou <zhquan7@gmail.com>
=> [doc] Clarify the behavior of the 'Data Status' and 'Overview' dashboards

README.md, sirmordred/config.py
This code enables the support of the survival study in mordred.
=> [config] Add support for `enrich_forecast_activity` study

README.md, sirmordred/config.py
This PR addresses https://github.com/chaoss/grimoirelab/issues/258
This code adds the study `enrich_feelings` to th list of available studies in GrimoireLab.
The study can be set up via the setup.cfg as follows
```
[github2]
api-token = ...
raw_index = github_chaoss_crossminer
enriched_index = github_chaoss_crossminer_enriched
sleep-for-rate = true
no-archive = true
studies = [enrich_feelings]
[enrich_feelings]
attributes = [title, body]
nlp_rest_url = http://localhost:2901
[github2:prs]
api-token = ...
raw_index = github-prs_chaoss_crossminer
enriched_index = github-prs_chaoss_crossminer_enriched
sleep-for-rate = true
category = pull_request
no-archive = true
studies = [enrich_feelings]
```
=> [config] Add `enrich_feelings` study

aliases.json, tests/aliases.json
Test data has been updated accordingly.
=> [aliases] Fix supybot alias `irc` instead of `supybot`

utils/setup.cfg
Removed two parameters from the example setup.cfg file.
=> Removed faulty parameter from utils/setup.cfg

README.md
Add ELASTICSEARCH_USER and ELASTICSEARCH_PASSWORD fields
in the docker-compose file to install the GrimoireLab components
Signed-off-by: Aditya <aditya10699@gmail.com>
=> [doc] fix docker-compose file

README.md
This code updates the README to include examples of dockersmells and dockerdeps used to collect dependencies and smells from Docker files.
Related to https://github.com/chaoss/grimoirelab/issues/262
=> [doc] Add instructions to use dockersmells and dockerdeps

README.md, sirmordred/config.py
This PR replaces https://github.com/chaoss/grimoirelab-sirmordred/pull/394. It includes the backlog analysis study to the config.py and update the readme accordingly.
=> [mordred] Add support for backlog analysis study

README.md
This commit adds the sample `projects.json` and `setup.cfg` for cocom.
=> [doc] Add sample cocom fields

requirements.txt, setup.py, sirmordred/task_panels.py, tests/test_task_panels.py
This code fixes the way the panels are loaded due to the recent change on kidash (commit:
https://github.com/chaoss/grimoirelab-kidash/commit/e8795023b31df726850b32e3f019a933ea614d5a) that has removed the dependency with sigils.
Now the task panels takes care of building the panels path, which consists of the sigils module plus the name of panels.
Dependencies in the requirements.txt and setup.py have been updated to include sigils.
Tests have been updated accordingly.
Fixes #410
=> [task_panels] Upload panels from the sigils module

setup.py, utils/panels_config.py
This code introduces a new script to assist the uploading of the top menu and dashboards by relying
on the task_panels.py logic. This is an initial exploration to separate the logic to upload the
panels from the rest of the platform.
Fixes: https://github.com/chaoss/grimoirelab-sirmordred/issues/147
=> [utils] Add script to upload menu and dashboards

utils/setup.cfg
This commit replaces actual api-token in
Gitlab config with a place holder xxxx
Signed-off-by: animesh <animuz111@gmail.com>
=> [micromordred] Replace actual api-token

requirements.txt, setup.py, utils/micro.py
Fixes Partially #423 
@valeriocos please review. 
Just wanted the opinion before porting the new logging system to sirmordred binary. I have currently added the logging support only for micro.py. Please use it (you may copy the code directly from here it's small, or use my branch) and review. You may try it for different scenarios like when there are several errors and look if the readability and user experience is improved. A new dependency `colorlog` is added which I am concerned of. I tried several ways but the solutions were either very large or not extensible. I found this one the most compact and suitable.
If the coloring is too subjective we can also add a argument maybe `--enhanced-log`, leaving it to the user whether to …
=> added color logging facility in micro.py

README.md
mariadb services for docker-compose.yml in "without searchguard" section
=> Corrected mariadb services for docker-compose.yml 

README.md, utils/micro.py
Added logging to file support for micro mordred. Now devs can use the `--logs-dir` argument followed by the directory name to enable logging into file. This enables easy sharing of logs for debugging purposes. Please review.
The logs are currently being appended to the same file. We can change that behaviour to either of the below:
* Create a new log file for every execution. In this case the name of the file will contain the timestamp of the corresponding execution.
* Simply replace the content of the old file when a new execution takes place. 
Same applies for sirmordred.
Which one should I go for?
=> [micro mordred]added logging to file support for micro.py

sirmordred/sirmordred.py
This PR removes the duplicate call of `execute_batch_tasks` function in `sirmordred.py` .
Fix #435 .
Signed-off-by: LinHaiming <lhming23@outlook.com>
=> [sirmordred] Remove duplicate call of execute_batch_tasks

Getting-Started.md
This code updates the kibiter image used in the docker-compose to 6.1.4-3, since the network plugin
isn't loaded in the current version.
=> [Getting-started] Update kibiter version to 6.1.4-3

README.md, sirmordred/task.py, sirmordred/task_collection.py
We need a way to anonymize the personal information that comes from Perceval: names, emails and information that may be related to the users of each backend must be hidden.
The information stored in the Elasticsearch indexes should only be identifiers that cannot be related directly with the user.
In this merge request, information related with the users is hashed or removed.
You can set the parameter `anonymize` to true in the sirmordred configuration:
```
[git]
...
anonymize = true
[github]
...
filter-classified = true
anonymize = true
[gitlab]
...
anonymize = true
[meetup]
...
anonymize = true
```
Related with issues https://github.com/chaoss/grimoirelab-sirmordred/issues/443 and https://github.com/chaoss/grimoirelab-elk/issues/822
Related with pull request: …
=> Make anonymization optional for each backend

Getting-Started.md
This PR revamps the structure of getting-started.md according to the recent discussion at https://github.com/chaoss/grimoirelab-sirmordred/pull/428#discussion_r392673572.
Hi @valeriocos 
I was working on this revamp. Please review this PR when you are free. 
I am yet to modify a few things here I guess. So, I will be leaving this PR open for a while for suggestions and improvements. Please let me know if you have any.
[Link](https://github.com/vchrombie/grimoirelab-sirmordred/blob/reshape-getting-started/Getting-Started.md) to view the changes.
/cc @abhiandthetruth @animeshk08, as you already involved in the previous discussion.
Also if anyone has any suggestions, please feel free to comment over here. 
Thanks. :slightly_smiling_face:
=> [docs] revamp of getting-started.md

README.md, sirmordred/config.py
This commit removes user and password from the documentation in Elasticsearch section because it is not used.
It also fixes a typo in Gitlab section
Q: Should we remove user and password from https://github.com/chaoss/grimoirelab-sirmordred/blob/master/sirmordred/config.py#L213?
=> Remove user and password parameter from Elasticsearch section

tests/archives-test.cfg
This code updates the archives-test.cfg to remove the user and password params in the es_enrichment section.
=> [tests] Remove user/password from es_enrichment section

README.md, aliases.json
This commit adds Pagure datasource
to README.
Commit addresses issue: https://github.com/chaoss/grimoirelab-elk/issues/821
Signed-off-by: Animesh Kumar <animuz111@gmail.com>
=> [doc] Add Pagure datasource

README.md
This parameter set which days of the month the
`enrich_git_branches` study will run.
=> [doc-git] Add parameter `run_month_days` in `enrich_git_branches`

README.md, aliases.json, sirmordred/config.py, sirmordred/task_panels.py
This code allows to upload the dashboard about github events using the param `github-events`, which must be set to true within the section `panels`.
Alias file has been updated accordingly.
Documentation has been updated accordingly.
=> [mordred] Add support for github events

README.md, sirmordred/task_identities.py
This code add the command `--no-enrollment-periods-validation`
when the `strict_mapping` is deactivated in the `setup.cfg` file.
=> [task_identities] add `no-enrollment-periods-validation`

requirements_tests.txt, sirmordred/task.py, sirmordred/task_collection.py, sirmordred/task_enrich.py
This code removes the credentials that appear in the URLs of Git private repos (defined within the
projects.json) in log messages. Furthermore, the method in charge of removing such credentials
have been modified to keep the protocol used (e.g., http and https).
=> [sirmordred] Remove credentials from private URLs

aliases.json
This code removes the aliases affiliations and all_enriched for github2:issue and github2:pull. This change is needed to avoid overlaps between the github and github2 data (which are similar).
=> [aliases] Remove affiliations and all_enriched aliases for github2

tests/test_task_panels.py
This code removes the test to create a dashboard in kibiter 5. This is removal is possible since ES/Kibiter 5.x isn't used in other parts of the platform.
=> [tests] Remove panels test for kibiter 5.x

sirmordred/task_panels.py
This PR allows to upload the label-related dashboard when the flag github-events in the section panel is set to True.
Related to https://github.com/chaoss/grimoirelab-sigils/pull/454
=> [task_panels] Upload label-related dashboard

README.md
This code adds an example to execute mordred on a rocketchat instance.
Related to https://github.com/chaoss/grimoirelab-elk/pull/890
=> [doc] Add instructions to mine rocketchat

README.md, sirmordred/config.py
This code adds supports for the duration analysis study. It also includes the documentation to execute it.
Related to https://github.com/chaoss/grimoirelab-elk/pull/893
=> [config] Add support for duration analysis

Getting-Started.md
Here is the screenshot of the current Getting-Started.md
As shown, there was a little inconsistency in the text displayed and the corresponding image.
Modified Getting-Started.md
=> Remove inconsistency in displaying images

menu.yaml
Needed once https://github.com/chaoss/grimoirelab-sigils/pull/457 is merged because the file name is fixed there.
There was a typo in GrimoireLab-Sigils and the name of the file
was misspelled.
Signed-off-by: Alberto Pérez García-Plaza <alpgarcia@bitergia.com>
=> Fix lifecycle file name

Getting-Started.md
There are two new main topics under the `How to` section:
* Handle identities assigned to "Unknown" organization
* Add a new organization/domain entry via Hatstall
This section is added after issue https://github.com/chaoss/grimoirelab-elk/issues/913.
=> Update Getting Started guide with identities management section

README.md, sirmordred/config.py, tests/test_config.py, tests/test_studies.cfg
This new study creates new fields to give us the first and last
date of different contribution types for each author.
Note: once there is a panel based on this study, `sirmordred/task_panels.py` has to be updated including the path to the corresponding JSON file with the index pattern
=> Add new study "demography_contribution"

tests/test_task_panels.py
This commit fixes the flake8 errors in the test_task_panels.py file which is causing the travis build failure.
=> [tests] Fix flake8 errors

Getting-Started.md
Signed-off-by: Sourabh Saraswat <saraswatsourabh5@gmail.com>
expose =>as it activates container to listen for a specific port only from the world inside of docker AND not accessible from world outside of the docker . So that's why this create an issue with connection to database when we run micro-mordred .
as per reference [https://docs.docker.com/engine/reference/builder/#expose](https://docs.docker.com/engine/reference/builder/#expose)
So to overcome this we can use :
ports =>  as it activates the container to listen for specified port(s) from the world outside of the docker AND also accessible world inside docker.
and there is one more issue while setting up grimoire lab from docker-compose (with SearchGuard) that it have no database with name of "test_sh" which creates an error "no …
=> [docs] Update the mariadb docker-compose configuration

utils/projects.json
Currently, projects.json contains an entry for gitlab-org/gitlab-ce as an example for both gitlab:issue and gitlab:merge.  However, attempting to run this with sirmordred (I tested with micromordred), this causes a 404 error, since this project has since since moved to gitlab-org/gitlab-foss.
This commit simply updates the examples in projects.json to the post-migration repo url.
=> Update gitlab example in utils/projects.json

.github/workflows/tests.yml, README.md, poetry.lock, pyproject.toml
This PR:
- Updates the GitHub actions tests to use Poetry. It runs the tests and also flake8.
- Update badges in the README.md
**This PR depends on https://github.com/chaoss/grimoirelab-sirmordred/pull/531. 3/4 commits are from that PR.**
=> [gha] Use poetry for tests

sirmordred/config.py
Everytime we add new enrich methods for backends, we need to change this place to add those new enrich methods. It is helpful that we can get study sections dynamically.
Signed-off-by: Fugang Xiao <xiao623@outlook.com>
=> [config] Get study sections dynamically

docker/Dockerfile
The base image we were using is old and deprecated. This change updates the image to the latest Debian
stable image, codenamed "bullseye".
=> Update base docker image to Debian "bullseye"

sirmordred/utils/setup.cfg
`menu_file` and `aliases_file` have moved in the directory structure since the last update of `setup.cfg`, and the updated paths for them in this change will fix the file not found errors upon running micro-mordred. This is a solution that does not move the positions of any files.
Fixes #538.
Signed-off-by: Mabel <70232089+mabelbot@users.noreply.github.com>
=> [utils] Update setup.cfg to reflect new file structure 

poetry.lock, pyproject.toml
Poetry doesn't check for pre-releases during dependency resolving of non-direct dependencies. `Grimoirelab` packages should be in the latest version.
`cereslib` and `graal` weren't in the old pyproject but are dependencies of `grimoire-elk` and part of the Grimoirelab stack.
=> Update Grimoirelab dependencies

docker/stage
This code removes temporary `perceval` files after a restart to avoid filling up the disk.
=> [docker/stage] Remove temporary perceval files

releases/unreleased/sortinghat-option-to-verify-ssl.yml, sirmordred/config.py, sirmordred/task.py, sirmordred/task_enrich.py
This PR includes a new method in the enrichment process to verify the connection to the SortingHat database when using SSL. By default, this option is set to True.
Depends on https://github.com/chaoss/grimoirelab-elk/pull/1101 and https://github.com/chaoss/grimoirelab-sortinghat/pull/737
=> [sortinghat] Include `verify_ssl` option for SortingHat

releases/unreleased/sirmordred-logs-available-on-console.yml, sirmordred/bin/sirmordred.py, sirmordred/config.py
This commit adds all SirMordred logs to console handler. Only when the `logs_dir` parameter in the `general` section is set, it will also write the logs in that file.
Now the `logs_dir` parameter is optional.
=> Add all logs to console handler

.github/workflows/release.yml
This PR updates the version of the release GitHub action to use ubuntu-latest instead of ubuntu-18.04 wich is deprecated.
=> [ci] Update deprecated ubuntu-18.04 of GitHub Actions

releases/unreleased/race-condition-initializing-sirmordred.yml, sirmordred/sirmordred.py, sirmordred/task_manager.py
When mordred starts, it loads the dashboards to Kibana and next, it reads the list of projects to analyze. Due to a race condition, the thread that reads the list of projects could not even start, so data backends won't have any input to work with.
This commit fixes the problem adding isolated code that will run the initial tasks. Once these tasks are finished, the main loop will start the task manager.
Fixes chaoss/grimoirelab#585
=> Fix race condition on initial tasks

releases/unreleased/refresh-identities-in-a-shorter-period.yml, sirmordred/sirmordred.py, sirmordred/task.py, sirmordred/task_autorefresh.py, sirmordred/task_enrich.py, tests/test_task_autorefresh.py
Create a new Global task that runs an autorefresh process for all the backends continuously. The period this Task is executed depends on the configuration defined by `sortinghat.sleep_for`.
=> [task] Create a new task that autorefreshes identities periodically

.github/workflows/release.yml, .github/workflows/tests.yml
This commit updates the version of the database for SortingHat. Now SortingHat requires Mariadb 10.4 or higher and MySQL 8.1 or higher.
=> [CI] Update mariadb version

releases/unreleased/days-in-collection-spent-time.yml, sirmordred/task_collection.py
When the collection phase is finished and the spent time is more than one day, days are missing in the logs. It is now fixed and included in the logs.
=> Include days spent in collection phase logs

releases/unreleased/identity-refresh-bug-for-some-items.yml, sirmordred/task_enrich.py
This PR resolves an issue where role identities (like `reviewed_by` or `merged_by` among others) were not refreshed.
The bug occurred because the queries to OpenSearch filtered items in which `author_uuid` was the individual pk, but not when the `<role>_uuid` was the individual pk. That causes many items that contain the `<role>_uuid` but not the `author_uuid` not to be refreshed.
For example, the `Author` role was not affected because it matched `author_uuid`, but roles like `reviewed_by` did not match and were missed.
This PR depends on https://github.com/chaoss/grimoirelab-elk/pull/1163
This PR fixes https://github.com/chaoss/grimoirelab-elk/issues/1161
=> Fix identity refresh bug for all roles

.github/workflows/release.yml, .github/workflows/tests.yml, poetry.lock, pyproject.toml, releases/unreleased/python-minimum-version-updated.yml, sirmordred/task.py
Python 3.8 will reach its end of life in October 2024, and Python 3.9 will become the minimum version required by the project.
Update the GitHub workflows to run tests for Python 3.9, 3.10, 3.11 and 3.12 for future releases.
Update some pinned dependencies due to old errors that seem to have been fixed.
Related to https://github.com/chaoss/grimoirelab/issues/699
=> Drop Python 3.8 support

releases/unreleased/tasks-not-requiring-sortinghat-fixed.yml, sirmordred/task_collection.py, sirmordred/task_identities.py, sirmordred/task_panels.py, sirmordred/utils/micro.py
Tasks that didn’t require the SortingHat client were failing or receiving incorrect arguments because the client was being passed as the second argument. Since the client is required for all tasks, it has been added as an argument in the subclass constructors.
=> Fix tasks without required SortingHat client

.github/workflows/release.yml, .github/workflows/tests.yml
This PR adds Python 3.12 tests to the GitHub Actions workflows. These tests were missing during the migration from 3.8 to 3.9 due to incompatibilities with NumPy and the available packages at that time.
=> Include Python 3.12 in workflow tests

.github/workflows/release.yml, .github/workflows/tests.yml, poetry.lock, pyproject.toml, releases/unreleased/increased-minimum-version-for-python-to-310.yml, sirmordred/task_autorefresh.py, sirmordred/task_enrich.py, tests/archives-test.cfg, tests/data/task-params-test.cfg, tests/test-no-collection.cfg, tests/test-repos.cfg, tests/test.cfg, tests/test_studies.cfg, tests/test_task_collection.py, tests/test_task_enrich.py, tests/test_wrong.cfg
Update workflows and configuration to support Python >3.10.
Python 3.9 will no longer receive updates after October 2025. This change ensures compatibility with newer features and maintains security for the project.
Remove `elasticsearch` package and use the latest version of `opensearch-py` for future development. This change makes ElasticSearch 6 no longer compatible. Include OpenSearch 2.x and 3.x in tests.
Simplify the workflow by using SortingHat commands, instead of cloning the main repository and using outdated commands.
=> Drop Python 3.9 and ElasticSearch 6 support
